name: Deploy Angular to Contabo

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci && npm run build -- --configuration=production

      - name: Verify build
        run: |
          [ -f dist/solidarite-plus/browser/index.html ] || exit 1

      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy files
        run: |
          rsync -avz --delete \
            -e 'ssh -o StrictHostKeyChecking=no' \
            ./dist/solidarite-plus/browser/ \
            root@${{ secrets.VPS_IP }}:/var/www/angular-app/

          ssh root@${{ secrets.VPS_IP }} "
            chown -R www-data:www-data /var/www/angular-app
            systemctl reload nginx
          "

      - name: Verify
        run: |
          curl -sf http://${{ secrets.VPS_IP }} || exit 1